import { Oxygen } from "next/font/google"; // Import Oxygen
import "./globals.css";
import { CartProvider } from "@/context/cartContext";
import { SessionProvider } from "next-auth/react";

// Configure Oxygen font
const oxygen = Oxygen({
  weight: ["300", "400", "700"], // Specify weights you want to use
  subsets: ["latin"],
  variable: "--font-oxygen", // Define a CSS variable for Oxygen
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oxygen.variable}`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
